### ISSUE TITLE
I just wanted to Say

### ISSUE THREAD

**Issue by iamsoorena** [intoli/slice#1]
I loved your Idea, actually I was thinking about making something like this myself.
But thank you for all your hard work.

**Comment by sangaline** [comment]
Thanks, we really appreciate the feedback!

**Comment by iamsoorena** [comment]
I'm ready to help you in this project, If there was a task you can assign to me. :D
I'm already [propagating this project](https://stackoverflow.com/a/51859182/5284370).

**Comment by sangaline** [comment]
That's awesome, thanks! There aren't really any outstanding issues right now because the interface replicates the Python slicing behavior completely (to the best of my knowledge). If you notice any bugs though, then that would be a great opportunity for a PR.

If you like the general idea here, then you might want to check out this [Recreating Python's Slice Syntax in JavaScript Using ES6 Proxies](https://intoli.com/blog/python-slicing-in-javascript/) article on the [Intoli Blog](https://intoli.com/blog/). It walks through the process of writing the library, and it has a lot of extra content that's not included in the README.
